const WHATSAPP='919581179117';
const STORE='manana360_v4_enquiries';
function qs(s,root=document){return root.querySelector(s)}
function qsa(s,root=document){return [...root.querySelectorAll(s)]}
function getEnquiries(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
function saveEnquiries(list){localStorage.setItem(STORE,JSON.stringify(list))}
function saveEnquiry(type,data){const list=getEnquiries();list.unshift({id:'M360-'+Date.now(),type,status:'New',createdAt:new Date().toLocaleString(),...data});saveEnquiries(list)}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function waLink(message){return `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`}
function bindForms(){qsa('[data-lead-form]').forEach(form=>{form.addEventListener('submit',e=>{e.preventDefault();const data=formData(form);const type=form.getAttribute('data-lead-form')||'lead';saveEnquiry(type,data);const msg=`Manana360 ${type} enquiry%0AName: ${data.name||''}%0AMobile: ${data.mobile||''}%0ABusiness: ${data.businessType||data.industry||''}%0ACity: ${data.city||''}%0ARequirement: ${data.requirement||''}`;alert('Thank you. Your enquiry is saved in V4 demo admin dashboard. Next step: connect Firebase for cloud saving.');form.reset();const openWa=form.getAttribute('data-whatsapp')==='true';if(openWa) window.open(waLink(msg),'_blank');});});qsa('[data-wa]').forEach(a=>{a.href=waLink(a.getAttribute('data-wa')||'I want Manana360 demo')});}
function renderAdmin(){const box=qs('#adminList');if(!box)return;const list=getEnquiries();qs('#totalLeads').textContent=list.length;qs('#newLeads').textContent=list.filter(x=>x.status==='New').length;qs('#demoLeads').textContent=list.filter(x=>String(x.type).includes('demo')).length;qs('#franchiseLeads').textContent=list.filter(x=>String(x.type).includes('franchise')).length;if(!list.length){box.innerHTML='<div class="notice">No enquiries yet. Submit a form from Contact / Franchise / Home page first.</div>';return}box.innerHTML=`<table class="table"><thead><tr><th>Date</th><th>Type</th><th>Name</th><th>Mobile</th><th>Business</th><th>Status</th></tr></thead><tbody>${list.map((x,i)=>`<tr><td>${x.createdAt}</td><td>${x.type}</td><td>${x.name||'-'}</td><td>${x.mobile||'-'}</td><td>${x.businessType||x.industry||'-'}</td><td><select data-status="${i}"><option ${x.status==='New'?'selected':''}>New</option><option ${x.status==='Contacted'?'selected':''}>Contacted</option><option ${x.status==='Demo Scheduled'?'selected':''}>Demo Scheduled</option><option ${x.status==='Closed'?'selected':''}>Closed</option></select></td></tr>`).join('')}</tbody></table>`;qsa('[data-status]').forEach(sel=>sel.addEventListener('change',()=>{const arr=getEnquiries();arr[sel.dataset.status].status=sel.value;saveEnquiries(arr);renderAdmin()}));}
function clearAdmin(){if(confirm('Clear local demo enquiries?')){localStorage.removeItem(STORE);renderAdmin()}}
document.addEventListener('DOMContentLoaded',()=>{bindForms();renderAdmin();const c=qs('#clearAdmin');if(c)c.addEventListener('click',clearAdmin)});
